package: builder
version: '1.0.0-beta1'
author: 'Friends of REDAXO'
supportpage: 'https://klxm.de'
license: MIT

requires:
    packages:
        yform: '>=4.0'
        focuspoint: '>=4.0'
    redaxo: '^5.15'
    php:
        version: '^8.1'

page:
    title: 'Builder'
    icon: builder-icon-logo
    perm: admin
    subpages:
        main:
            title: 'translate:builder_overview'
            icon: rex-icon fa-info-circle
        modules:
            title: 'translate:builder_modules'
            icon: rex-icon fa-code
        media_types_preview:
            title: 'translate:builder_media_types_preview'
            icon: rex-icon fa-image
        settings:
            title: 'translate:builder_settings'
            icon: rex-icon fa-cog
        docs:
            title: 'translate:builder_docs'
            icon: rex-icon fa-book
            subPath: README.md
        dev:
            title: 'translate:builder_dev'
            icon: rex-icon fa-code
            subPath: DEV.md
        api:
            title: 'translate:builder_api'
            icon: rex-icon fa-code-fork
            subPath: API.md
        tutorial:
            title: 'translate:builder_tutorial'
            icon: rex-icon fa-graduation-cap
            subPath: TUTORIAL.md
