package: builder
version: '1.0.0-beta7'
author: 'Friends of REDAXO'
supportpage: 'https://klxm.de'
license: MIT

requires:
    packages:
        media_manager: '*'
    redaxo: '^5.20.1'
    php:
        version: '^8.1'

page:
    title: 'Builder'
    icon: builder-icon-logo
    perm: builder[]
    subpages:
        main:
            title: 'Demo'
            icon: rex-icon fa-info-circle
            perm: builder[]
        demo:
            title: 'Demo'
            icon: rex-icon fa-play-circle
            perm: builder[]
            hidden: true
        modules:
            title: 'translate:builder_modules'
            icon: rex-icon fa-code
            perm: admin
        settings:
            title: 'translate:builder_settings'
            icon: rex-icon fa-cog
            perm: admin
        media_types_preview:
            title: 'translate:builder_media_types_preview'
            icon: rex-icon fa-image
            perm: admin
        settings_yform_list_profiles:
            title: 'translate:builder_yform_list_profiles'
            icon: rex-icon fa-table
            perm: admin
        docs:
            title: 'translate:builder_docs'
            icon: rex-icon fa-book
            perm: builder[]
            itemClass: pull-right
