package: builder
version: '1.0.0-beta5'
author: 'Friends of REDAXO'
supportpage: 'https://klxm.de'
license: MIT

requires:
    packages:
        media_manager: '*'
    redaxo: '^5.15'
    php:
        version: '^8.1'

page:
    title: 'Builder'
    icon: builder-icon-logo
    perm: admin
    subpages:
        main:
            title: 'translate:builder_overview'
            icon: rex-icon fa-info-circle
        demo:
            title: 'Demo'
            icon: rex-icon fa-play-circle
        modules:
            title: 'translate:builder_modules'
            icon: rex-icon fa-code
        media_types_preview:
            title: 'translate:builder_media_types_preview'
            icon: rex-icon fa-image
        settings:
            title: 'translate:builder_settings'
            icon: rex-icon fa-cog
        settings_yform_list_profiles:
            title: 'translate:builder_yform_list_profiles'
            icon: rex-icon fa-table
        docs:
            title: 'translate:builder_docs'
            icon: rex-icon fa-book
